# Generated by Django 5.1.6 on 2025-02-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
